config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/view'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "homepage#index"

  get 'payments/new' => 'payments#new'
  post 'payments' => 'payments#create'
  get 'payments/success' => 'payments#success'
  get 'redirect_to_root', to: 'dashboard#redirect'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # columns: name, email, stripe_token
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def view

  end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

def index
   token = cookies[:stripe_token]
   user = User.find_by(stripe_token:token)
   p user
   if user
    redirect_to dashboard_view_path
   else
    render :index
   end

end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
  end

  def create
    @amount = 99
  payment_method = Stripe::PaymentMethod.create({
    type: 'card',
    card: {
      token: params[:stripeToken]
    }
  })


  payment_intent = Stripe::PaymentIntent.create({
    amount: @amount,
    currency: 'USD',
    payment_method_types: ['card'],
    payment_method: payment_method.id,
    confirm: true,
    use_stripe_sdk: true,
    setup_future_usage: 'off_session'
  })

  if payment_intent.status == 'requires_action'
      authentication_url = payment_intent.next_action.use_stripe_sdk.stripe_js
      user = User.new({name:params[:name],email:params[:email],stripe_token:params[:stripeToken]})
      if user.save
        cookies[:stripe_token] = params[:stripeToken]
        redirect_to authentication_url, allow_other_host: true
      else
        redirect_to root_path
      end
   else
      user = User.new({name:params[:name],email:params[:email],stripe_token:params[:stripeToken]})
      if user.save
        cookies[:stripe_token] = params[:stripeToken]
          redirect_to dashboard_view_path
        else
          redirect_to root_path
      end
  end

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path
  end

  def success
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/dashboard/view.html.erb
<div class="text-center" style="height: 700px; width:100%">
<h1>Welcome to the dashboard, you already subscribed.</h1>

</div>

app/views/homepage/index.html.erb
<div class="d-flex flex-column">

<div class="w-100 d-flex flex-column align-items-center text-center mt-2" style="height:100px;">
  <div>
   <h2 class="text-indigo fw-bold f-base text-30px">PRICING</h2>
  </div>
  <div class="w-25 text-center">
   <p class="text-wrap f-base text-17px">Subscribe in less then 30 seconds. Try out our 7 days risk free trial upgrade at anytime, no question, no hustle.</p>
  </div>

 
</div>

<div class="w-100 d-flex flex-column mx-auto mt-5 align-items-center" >
  <div class="btn btn-custom" style="font-size:16px;">Popular plan</div>
</div>

<div class="w-100 d-flex flex-row justify-content-center mt-5" >
  <div class="card-1 mt-5 d-flex flex-column text-center justify-content-around">
      <div class="mt-5">
        <h1 class="text-25px fw-bold" style="font-weight:bold">Free</h1>

        <h2 class="mt-4">$0/month</h2>
      <div class="d-flex flex-column text-14px mt-5 f-base">
      <span><i class="fa-solid fa-check "></i> Up to 100 emails per day</span>
      <span><i class="fa-solid fa-check"></i> Up to 100 emails per day</span>
      <span><i class="fa-solid fa-check"></i> Up to 100 emails per day</span>

      </div>
      </div>

      <div class="w-100 d-flex flex-column mx-auto align-items-center" >
        <button class="btn btn-custom-2 f-base fw-bold" type="button" style="font-size:16px;">Signup</button>
      </div>

  </div>

  <div class="card-2 d-flex flex-column text-center justify-content-around">
      <div class="mt-5 f-base">
        <h1 class="text-25px fw-bold" style="font-weight:bold">Standard</h1>

        <h2 class="mt-4 f-base">$99/month</h2>
      <div class="d-flex flex-column text-14px mt-5 f-base">
      <span><i class="fa-solid fa-check "></i> Lorem Ipsum is simply dummy text </span>
      <span><i class="fa-solid fa-check"></i> Lorem Ipsum is simply dummy text </span>
      <span><i class="fa-solid fa-check"></i> Lorem Ipsum is simply dummy text </span>

      </div>
      </div>

      <div class="w-100 d-flex flex-column mx-auto align-items-center f-base" >
        <button class="btn btn-custom f-base fw-bold" type="button" onclick="showModal()" style="font-size:16px;">Subscribe</button>
      </div>


  </div>
  <div class="card-1 mt-5 d-flex flex-column text-center justify-content-around">
      <div class="mt-5">
        <h1 class="text-25px fw-bold" style="font-weight:bold">Enterprise</h1>

        <h2 class="mt-4">$399/month</h2>
      <div class="d-flex flex-column text-14px mt-5 f-base">
      <span><i class="fa-solid fa-check "></i> Up to 100 emails per day</span>
      <span><i class="fa-solid fa-check"></i> Up to 100 emails per day</span>
      <span><i class="fa-solid fa-check"></i> Up to 100 emails per day</span>

      </div>
      </div>

      <div class="w-100 d-flex flex-column mx-auto align-items-center" >
        <button class="btn btn-custom-2 f-base fw-bold" type="button" style="font-size:16px;" onclick="showModal()">Signup</button>
      </div>

  </div>

</div>

</div>


<div id="paymentModal" class="modal">
  <div class="modal-content-1">
  <div class="card-3" style="margin-top:25%">
    <%= form_tag(payments_path, id: "payment-form") do %>
      <div class="form-group text-center">
        <label for="card-element" class="text-17px">
          Payment Details
        </label>
        <div ><input type="text" id="name" name="name" class="form-input" placeholder="Names" class="mt-5" ></div>
        <div ><input type="text" id="email" name="email" class="form-input mt-4" placeholder="Email"></div>
        <div id="card-element" class="mt-4">
        </div>
        <div id="card-errors" role="alert"></div>
      </div>
      <div class="w-100 d-flex flex-column mx-auto align-items-center" >
        <button class="btn btn-custom f-base fw-bold mt-4" type="submit" style="font-size:16px;">Make Payment</button>
      </div>
    <% end %>
  </div>
  </div>
</div>



<script src="https://js.stripe.com/v3/"></script>
<script>
  var stripe = Stripe('pk_test_51MNs51EBYr4Xth1xY8YDuS7LrsjCjO0ox9N8P8wrggjzZEuDVLl3nREMSGdbBs1r97ndEdyQ8KFHcIjn5zy4e6iH006oXdkcHv');
  var elements = stripe.elements();
  var cardElement = elements.create('card');
  cardElement.mount('#card-element');

  var form = document.getElementById('payment-form');
  form.addEventListener('submit', function(event) {
    event.preventDefault();

    stripe.createToken(cardElement).then(function(result) {
      if (result.error) {
        var errorElement = document.getElementById('card-errors');
        errorElement.textContent = result.error.message;
      } else {
        stripeTokenHandler(result.token);
      }
    });
  });

  function stripeTokenHandler(token) {
    var form = document.getElementById('payment-form');
    var hiddenInput = document.createElement('input');
    hiddenInput.setAttribute('type', 'hidden');
    hiddenInput.setAttribute('name', 'stripeToken');
    hiddenInput.setAttribute('value', token.id);
    form.appendChild(hiddenInput);
    form.submit();
  }



var modal = document.getElementById("paymentModal");

function showModal() {
  modal.style.display = "block";
}

function hideModal() {
  modal.style.display = "none";
}

window.onclick = function (event) {
  if (event.target == modal) {
    hideModal();
  }
}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StripeSubsctiption</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'stripe_elements' %>
    <%= stylesheet_link_tag 'modals' %>
    <%= javascript_include_tag 'modals' %>

    <%= javascript_importmap_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


  </head>

  <body>
    <header>
      <%= render :partial => 'shared/header' %>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      <%= render :partial => 'shared/footer' %>
    </footer>
  </body>

</html>

app/views/shared/_footer.html.erb
<div class=" w-100">
  <footer class="text-center text-lg-start text-white w-100" style="background-color: #1c2331; width:100%">
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <div class="row mt-3">
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold f-base text-14px">Company name</h6>
            <hr class="mb-4 mt-0 d-inline-block mx-auto f-base " style="width: 60px; background-color: #7c4dff; height: 2px"/>
            <p class="text-13px">John MUGIRANEZA Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
          </div>
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold f-base text-14px">Company</h6>
            <hr class="mb-4 mt-0 d-inline-block mx-auto" style="width: 60px; background-color: #7c4dff; height: 2px"/>
            <p class="text-13px"><a href="#!" class="text-white f-base">Design</a></p>
            <p class="text-13px"><a href="#!" class="text-white f-base">Beveloper</a></p>
            <p class="text-13px"><a href="#!" class="text-white f-base">Full-stack</a></p>
            <p class="text-13px"><a href="#!" class="text-white f-base">Help</a> </p>
          </div>

          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4 f-base">
            <h6 class="text-uppercase fw-bold f-base text-14px">Contact</h6>
            <hr class="mb-4 mt-0 d-inline-block mx-auto" style="width: 60px; background-color: #7c4dff; height: 2px"/>
            <p class="text-13px"><i class="fas fa-home mr-3 "></i> Remote</p>
            <p class="text-13px"><i class="fas fa-envelope mr-3"></i> mujohn25@gmail.com</p>
            <p class="text-13px"><i class="fas fa-phone mr-3"></i> + 250 7855 71790</p>
          </div>
        </div>
      </div>
    </section>

    <div class="text-center p-3 f-base text-13px" style="background-color: rgba(0, 0, 0, 0.2)" >
      © 2023 Copyright:
      <a class="text-white f-base text-13px">mujohn25</a>
    </div>
  </footer>

</div>

app/views/shared/_header.html.erb
<header class="navbar navbar-bright navbar-fixed-top" role="banner">
  <div class="container">
    <div class="navbar-header">
    </div>
  </div>
</header>